#!/usr/bin/python3

import sys

def to_int(arg):
    try:
        return int(arg)
    except ValueError:
        exit(84)


def to_float(arg):
    try:
        return float(arg)
    except ValueError:
        exit(84)

def error_manager():
    if len(sys.argv) == 0:
        exit(84)
    elif len(sys.argv) == 2 and sys.argv[1] != "-h":
        exit(84)
    elif len(sys.argv) % 2 == 0:
        exit(84)


def display_help():
    if sys.argv[1] == "-h":
        print(
            "USAGE" "\n"
            "\t" "./107transfer [num den]*" "\n"
            "\n"
            "DESCRIPTION" "\n"
            "\t" "num" "\t" "polynomial numerator defined by its coefficients" "\n"
            "\t" "den" "\t" "polynomial denominator defined by its coefficients" "\n"
        )
        return 1
    return 0


def hormer_func(x, num_str, den_str):
    if (num_str == den_str):
        return (1.0)
    i = len(num_str) - 1
    num = 0.0
    den = 0.0
    while (i >= 0):
        num *= x
        num += to_float(num_str[i])
        i -= 1
    i = len(den_str) - 1
    while (i >= 0):
        den *= x
        den += to_float(den_str[i])
        i -= 1
    if den == 0:
        exit(84)
    result = to_float(num / den)
    return (result)


def run():
    x = 0.000
    while x <= 1.001:
        i = 1
        result = 1.0
        while i < len(sys.argv):
            num_str = sys.argv[i].split("*")
            den_str = sys.argv[i+1].split("*")
            result *= hormer_func(x, num_str, den_str)
            i += 2
        print("{0:.3f} -> {1:.5f}".format(x, result))
        x += 0.001


def main():
    error_manager()
    if not display_help():
        run()


if __name__ == '__main__':
    main()
