#!/usr/bin/python3

import math
import sys
import os


def to_int(arg):
    try:
        return int(arg)
    except ValueError:
        exit(84)


def to_float(arg):
    try:
        return float(arg)
    except ValueError:
        exit(84)


def error_manager():
    if len(sys.argv) != 2:
        exit(84)
    if sys.argv[1] != "-h":
        n = to_int(sys.argv[1])
        if n < 0:
            exit(84)
    return (0)

def frange(start, end=None, i=None):
    if end is None:
        end = start + 0.0
        start = 0.0
    if i is None:
        i = 1.0
    result = []
    while 1:
        next = start + len(result) * i
        if i > 0 and next >= end:
            break
        elif i < 0 and next <= end:
            break
        result.append(next)
    return result

def display_help():
    if sys.argv[1] == "-h":
        print(
            "USAGE" "\n"
            "\t" "./110borwein n" "\n"
            "\n"
            "DESCRIPTION" "\n"
            "\t" "n" "\t" "constant defining the integral to be computed"
        )
        return 1
    return 0

def function(x):
    result = 1
    if x == 0:
        return 1
    for nb in range(0, to_int(sys.argv[1])+1):
        result *= (math.sin(x / (nb*2+1))) / (x / (nb*2+1))
    return result


def midpoint_method():
    a = 0
    b = 0
    result = 0

    for i in frange(0, 5000, 0.5):
        a = i
        b = i+0.5
        result += function((a+b)/2) * 0.5
    print("Midpoint:")
    print("I{0} = {1:.10f}".format(to_int(sys.argv[1]), result))
    diff = abs(result - math.pi/2)
    print("diff = {0:.10f}".format(diff))
    return 0


def trapezoidal_method():
    a = 0
    b = 0
    result = 0

    for i in frange(0, 5000, 0.5):
        a = i
        b = i+0.5
        result += ((function(a) + function(b)) / 2) * 0.5
    print("Trapezoidal:")
    print("I{0} = {1:.10f}".format(to_int(sys.argv[1]), result))
    diff = abs(result - math.pi/2)
    print("diff = {0:.10f}".format(diff))
    return 0


def simpson_method():
    a = 0
    b = 0
    result = 0

    for i in frange(0, 5000, 0.5):
        a = i
        b = i+0.5
        result += ((function(a) + function(b) + 4 * function((a + b) / 2)) / 6) * 0.5
    print("Simpson:")
    print("I{0} = {1:.10f}".format(to_int(sys.argv[1]), result))
    diff = abs(result - math.pi/2)
    print("diff = {0:.10f}".format(diff))
    return 0


def run():
    midpoint_method()
    print()
    trapezoidal_method()
    print()
    simpson_method()
    return 0


def main():
    error_manager()
    if not display_help():
        run()
    return 0


if __name__ == '__main__':
    main()
